### ISSUE TITLE
Deb package for anax

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/horizon-deb-packager#1]
@bmpotter commented on [Fri Apr 21 2017](https://github.com/open-horizon/anax/issues/185)

**Comment by michaeldye** [comment]
Finished and tested (2.0.13 is in "prod" channel, raspbian jessie and ubuntu xenial ; 2.0.17 is in "staging" channel: raspbian jessie-testing and ubuntu xenial-testing).

**Comment by bmpotter** [comment]
Address jetson build index issue

**Comment by michaeldye** [comment]
Built arm64 packages for version 2.1.0 by hand and uploaded them to the objectstore: 

http://1DD40.http.tor01.cdn.softlayer.net/horizon-deb-test/horizon_2.1.0~ppa~ubuntu.xenial_arm64.deb

http://1DD40.http.tor01.cdn.softlayer.net/horizon-deb-test/bluehorizon_2.1.0~ppa~ubuntu.xenial_arm64.deb

These packages cannot be automatically built and indexed in the apt repo until I resolve the indexing issue with source packages from different architectures.
